import Transaction from "./TransactionIcon.svg";
import Master from "./Master.svg";
import Merchant from "./Merchant.svg";
import Shield from "./Shield.svg";
import User from "./User.svg";
import Plus from "./Plus.svg";
import Home from "./Home.svg";
import Vault from "./Vault.svg";
import Coins from "./Coins.svg";
import Vote from "./Vote.svg";
import Trophy from "./Trophy.svg";
import CircleTick from "./CircleTick.svg";
import External from "./External.svg";
import ThumbsUp from "./ThumbsUp.svg";
import ThumbsDown from "./ThumbsDown.svg";
import Info from "./Info.svg";
import Close from "./Close.svg";
import DownChevron from "./DownChevron.svg";
import UserCircle from "./UserCircle.svg";
import Search from "./Search.svg";
import Power from "./Power.svg";
import Alert from "./Alert.svg";
import Bin from "./Bin.svg";
import Expand from "./Expand.svg";
import Tick from "./Tick.svg";

export const TransactionIcon = Transaction;
export const MasterIcon = Master;
export const MerchantIcon = Merchant;
export const ShieldIcon = Shield;
export const UserIcon = User;
export const PlusIcon = Plus;
export const HomeIcon = Home;
export const VaultIcon = Vault;
export const CoinsIcon = Coins;
export const VoteIcon = Vote;
export const TrophyIcon = Trophy;
export const CircleTickIcon = CircleTick;
export const ExternalIcon = External;
export const ThumbsUpIcon = ThumbsUp;
export const ThumbsDownIcon = ThumbsDown;
export const InfoIcon = Info;
export const CloseIcon = Close;
export const DownChevronIcon = DownChevron;
export const UserCircleIcon = UserCircle;
export const SearchIcon = Search;
export const PowerIcon = Power;
export const AlertIcon = Alert;
export const BinIcon = Bin;
export const ExpandIcon = Expand;
export const TickIcon = Tick;
